import { getPublicSiteOrigin } from '@/lib/siteOrigin';

export const SITE_NAME = 'Tailnote';

export const SITE_TAGLINE = 'Turn every email into a marketing moment';

export const SITE_TITLE_DEFAULT = `${SITE_NAME} | ${SITE_TAGLINE}`;

/** Suffix highlighted in the home hero H1 gradient. */
export const SITE_TAGLINE_GRADIENT_SUFFIX = 'marketing moment';

/** Open Graph / Twitter large-card dimensions (1.91:1). */
export const OG_IMAGE_WIDTH = 1200;
export const OG_IMAGE_HEIGHT = 630;

/** Generated by app/opengraph-image.tsx (Next.js file convention). */
export const DEFAULT_OG_IMAGE_PATH = '/opengraph-image';

/** Organization logo for JSON-LD (not the social preview card). */
export const ORGANIZATION_LOGO_PATH = '/images/tailnote-logo.png';

export const DEFAULT_DESCRIPTION = `${SITE_TAGLINE} — on-brand signatures, promotional blocks, UTM tracking, and signature layouts for Gmail and Outlook.`;

/** Page title for subpages: `Page title | Tailnote`. */
export function formatPageTitle(pageTitle: string): string {
  return `${pageTitle} | ${SITE_NAME}`;
}

/** Canonical site origin for metadata, sitemap, and JSON-LD. */
export function getSiteUrl(): string {
  return getPublicSiteOrigin() ?? 'http://localhost:3000';
}

export function absoluteUrl(path: string): string {
  const base = getSiteUrl();
  const normalized = path.startsWith('/') ? path : `/${path}`;
  return `${base}${normalized}`;
}

export function absoluteOgImageUrl(): string {
  return absoluteUrl(DEFAULT_OG_IMAGE_PATH);
}

export function absoluteOrganizationLogoUrl(): string {
  return absoluteUrl(ORGANIZATION_LOGO_PATH);
}

/** Warn at build time when production deploy lacks a public site URL. */
export function warnProductionSiteUrl(): void {
  if (process.env.VERCEL_ENV !== 'production') return;
  const url = getSiteUrl();
  if (url.includes('localhost') || url.includes('127.0.0.1')) {
    console.warn(
      '[seo] Production build: set NEXT_PUBLIC_APP_URL (or NEXT_PUBLIC_SITE_URL) to your live domain. ' +
        'Sitemap, canonical URLs, and JSON-LD are using localhost.'
    );
  }
}
